ZoidbergStudios/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
     url(r'^$', 'dicom_visio.views.home_page', name='home'),
     url(r'^dicom_visio/', include('dicom_visio.urls'))
    #url(r'^admin/', include(admin.site.urls))',
]

dicom_visio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
     url(r'^(\d+)/$', 'dicom_visio.views.view_dicom', name='view_dicom'),
     url(r'^(\d+)/add_datum$', 'dicom_visio.views.add_datum', name='add_datum'),
     url(r'^new$', 'dicom_visio.views.new_dicom', name='new_dicom')
    #url(r'^admin/', include(admin.site.urls)),
]

dicom_visio/models.py
from django.db import models

class Dicom(models.Model):
    pass

class MDatum(models.Model):
    text = models.TextField(default='')
    dicom = models.ForeignKey(Dicom, default='')

dicom_visio/views.py
from django.shortcuts import redirect, render

from dicom_visio.models import MDatum, Dicom

def home_page(request):
    return render(request, 'home.html')

def view_dicom(request, dicom_id):
    dicom = Dicom.objects.get(id=dicom_id)
    return render(request, 'dicom.html', {'dicom':dicom})

def new_dicom(request):
    dicom = Dicom.objects.create()
    MDatum.objects.create(text=request.POST['metadata_text'], dicom=dicom)
    return redirect('/dicom_visio/%d/' % (dicom.id, ))

def add_datum(request, dicom_id):
    dicom = Dicom.objects.get(id=dicom_id)
    MDatum.objects.create(text=request.POST['metadata_text'], dicom=dicom)
    return redirect('/dicom_visio/%d/' % (dicom.id, ))

dicom_visio/templates/dicom.html
<html>
    <head>
        <title>Zoidberg's Studios</title>
    </head>
    <body>
        <h1>Zoidberg's Studios</h1>
        <table id="id_metadata_table">
            <tr>
                <th>Metadata</th>
            </tr>
            <tr><td><i>default metadata here</i></td></tr>
            <tr><td><i>Note: I'll design the model to have mdatum name and text</i></td></tr>
            {% for mdatum  in dicom.mdatum_set.all %}
                <tr><td>{{ mdatum.text }}</td></tr>
            {% endfor %}
        </table>
        <form method="POST" action="/dicom_visio/{{ dicom.id }}/add_item">
            <input name='metadata_text' id="id_change_metadata" placeholder="default metadata here"/>
            {% csrf_token %}
        </form>
    </body>
</html>

dicom_visio/templates/dicom_file.html
<html>
    <head>
        <title>Zoidberg's Studios</title>
    </head>
    <body>
        <h1>Zoidberg's Studios</h1>
        <table id="id_metadata_table">
            <tr>
                <th>Metadata</th>
            </tr>
            <tr><td><i>default metadata here</i></td></tr>
            <tr><td><i>Note: I'll design the model to have mdatum name and text</i></td></tr>
            {% for mdatum  in mdata %}
                <tr><td>{{ mdatum.text }}</td></tr>
            {% endfor %}
        </table>
        <form method="POST" action="/dicom_visio/new">
            <input name='metadata_text' id="id_change_metadata" placeholder="default metadata here"/>
            {% csrf_token %}
          </form>
    </body>
</html>

dicom_visio/templates/home.html
<html>
    <head>
        <title>Zoidberg's Studios</title>
    </head>
    <body>
        <h1>Zoidberg's Studios</h1>
        <form method="POST" action="/dicom_visio/new">
            <input name='metadata_text' id="id_change_metadata" placeholder="default metadata here"/>
            {% csrf_token %}
        </form>
    </body>
</html>